### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference goroutine 1

### ISSUE THREAD

**Issue by alimirrajei** [leukipp/cortile#15]
```
FATA[2023-06-15T07:37:16+03:30] runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x65
main.run.func1()
	/home/runner/work/cortile/cortile/main.go:49 +0x3d
panic({0x5f0720, 0x7e54e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/leukipp/cortile/desktop.(*Workspace).IsEnabled(...)
	/home/runner/work/cortile/cortile/desktop/workspace.go:109
github.com/leukipp/cortile/desktop.(*Tracker).Update(0xc00014a8e0)
	/home/runner/work/cortile/cortile/desktop/tracker.go:61 +0x68
github.com/leukipp/cortile/desktop.(*Tracker).onStateUpdate(0xc00014a8e0, {0xc0003be9a8, 0x13})
	/home/runner/work/cortile/cortile/desktop/tracker.go:357 +0x253
github.com/leukipp/cortile/common.stateCallbacks(...)
	/home/runner/work/cortile/cortile/common/root.go:200
github.com/leukipp/cortile/common.stateUpdate(0x411736?, {0x7f80bc568778?})
	/home/runner/work/cortile/cortile/common/root.go:184 +0x552
github.com/BurntSushi/xgbutil/xevent.PropertyNotifyFun.Run(0x5eec80?, 0xc0000a3230?, {0x606040?, 0xc0003be978?})
	/home/runner/go/pkg/mod/github.com/!burnt!sushi/xgbutil@v0.0.0-20190907113008-ad855c713046/xevent/callback.go:311 +0x38
github.com/BurntSushi/xgbutil/xevent.runCallbacks(0xc00022c000, {0x606040, 0xc0003be978}, 0xc00022c000?, 0x67cbc8?)
	/home/runner/go/pkg/mod/github.com/!burnt!sushi/xgbutil@v0.0.0-20190907113008-ad855c713046/xevent/xevent.go:203 +0x11c
github.com/BurntSushi/xgbutil/xevent.processEventQueue(0xc00022c000, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/!burnt!sushi/xgbutil@v0.0.0-20190907113008-ad855c713046/xevent/eventloop.go:253 +0x1065
github.com/BurntSushi/xgbutil/xevent.mainEventLoop(0xc00022c000, 0xc0001b0050?, 0x1?, 0x0)
	/home/runner/go/pkg/mod/github.com/!burnt!sushi/xgbutil@v0.0.0-20190907113008-ad855c713046/xevent/eventloop.go:108 +0x48
github.com/BurntSushi/xgbutil/xevent.Main(...)
	/home/runner/go/pkg/mod/github.com/!burnt!sushi/xgbutil@v0.0.0-20190907113008-ad855c713046/xevent/eventloop.go:52
main.run()
	/home/runner/work/cortile/cortile/main.go:64 +0x85
main.main()
	/home/runner/work/cortile/cortile/main.go:43 +0xaf
```

When I suspend xfce and then try to resume, I encounter an error message saying "invalid memory address or nil pointer dereference" and cortile is killed. I have already turned off the screensaver and lock screen, but this did not solve the problem. Could someone please help me resolve this issue? Thank you.

By the way, my Linux distribution is Void Linux.

**Comment by leukipp** [comment]
I have made some major code changes on the newest version. Please install the [latest](https://github.com/leukipp/cortile/releases/latest) version from scratch (deleting the existing `config.toml`) and post the most recent crash log, if the error still occurs.

**Comment by leukipp** [comment]
Actually I don't have a way to reproduce your issue atm. I added some error logging and validation on the develop branch. Please try to follow the [install instructions](https://github.com/leukipp/cortile/tree/main#development-) for development,  (e.g. Option 1) and run cortile with -vv. 

Let me then know what the latest entries in the log file are.

**Comment by leukipp** [comment]
```bash
#...
DEBU[2023-06-18T22:41:37+03:30] Update client info [Xfce4-terminal]          
DEBU[2023-06-18T22:41:37+03:30] GetLayout from dbus interface com.canonical.dbusmenu [0 -1 [type label visible enabled children-display accessible-desc]] 
DEBU[2023-06-18T22:41:37+03:30] GetGroupProperties from dbus interface com.canonical.dbusmenu [[0 1 2 3] []] 
# suspend
INFO[2023-06-18T22:41:46+03:30] Screens []                                   
INFO[2023-06-18T22:41:46+03:30] Desktops []                                  
INFO[2023-06-18T22:41:46+03:30] State event _NET_DESKTOP_LAYOUT
#...
```

For some reasons your environment reports that no screens are connected. 

We will need to go back and forth some more time.
Please try the latest `develop` version, where I ignore invalid screen updates.

**Comment by leukipp** [comment]
This fix is now also included in the [latest](https://github.com/leukipp/cortile/releases/latest) published version.

**Comment by leukipp** [comment]
There might be some new issues related to system suspension caused by this commit (346a89b). If you are still using cortile, it would be helpful if you could confirm that version [v2.3.0](https://github.com/leukipp/cortile/releases/tag/v2.3.0) is working as expected.
