### ISSUE TITLE
[Bug] Crash : "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by KaKi87** [leukipp/cortile#25]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5e9403]

goroutine 3212 [running]:
github.com/leukipp/cortile/store.(*Client).UnLock(...)
        /home/runner/work/cortile/cortile/store/client.go:78
github.com/leukipp/cortile/desktop.(*Tracker).onPointerUpdate.func1()
        /home/runner/work/cortile/cortile/desktop/tracker.go:439 +0xc3
created by time.goFunc
        /opt/hostedtoolcache/go/1.18.10/x64/src/time/sleep.go:176 +0x32
```

Thanks

**Comment by leukipp** [comment]
Should be fixed now. If any new problems arise, please report them by reopening this issue or creating a new one with log files attached.
